# Generated by Django 3.1 on 2020-08-25 13:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0002_auto_20200821_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('street_address', models.CharField(max_length=200)),
                ('municipality', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='The ZIP code does not match a NNNNN or NNNNN-NNNN format', regex='^[0-9]{5}\\-?(?:[0-9]{4})?$')])),
                ('pra_email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Public Records Email')),
                ('is_agency', models.BooleanField(default=True, verbose_name='Is the entity a public body (i.e. subject to public records law)?')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foia.state')),
            ],
            options={
                'verbose_name_plural': 'entities',
            },
        ),
    ]
