# Generated by Django 3.1.1 on 2020-09-17 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foia", "0009_auto_20200917_0621"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestcontent",
            name="content",
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(
                        2, message="Enter two or more character"
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="requestcontent",
            name="subject_line",
            field=models.CharField(
                max_length=80,
                validators=[
                    django.core.validators.MinLengthValidator(
                        2, message="Please have a subject with two or more characters"
                    )
                ],
            ),
        ),
    ]
