# Generated by Django 3.1.1 on 2020-09-19 05:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("foia", "0012_requestitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestitem",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="foia.pratemplate",
            ),
        ),
        migrations.CreateModel(
            name="GMailContact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("i", "Initiated Contact"),
                            ("f", "Followed Up"),
                            ("r", "Responded to Contact"),
                            ("ri", "Source initiated contact"),
                            ("rn", "Source sent notification"),
                            ("rr", "Source responded"),
                            ("rf", "Source followed up"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "contact_method",
                    models.CharField(
                        choices=[
                            ("r", "E-mail"),
                            ("p", "Phone"),
                            ("m", "Messaging system (not email)"),
                            ("o", "Other"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "contact_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("thread_id", models.CharField(max_length=64)),
                (
                    "related_request",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="foia.requestitem",
                    ),
                ),
                (
                    "responding_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="foia.gmailcontact",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
